name: ci

on:
  push:
  pull_request:
  release:
    types: [released, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'

      - name: Build
        run: dotnet build -c Release

      - name: Publish linux
        if: ${{ github.event_name == 'release' }}
        run: dotnet publish --output ./bin/publish/linux-x64 -r linux-x64 -c Release --self-contained -p:PublishSingleFile=true

      - name: Publish win
        if: ${{ github.event_name == 'release' }}
        run: dotnet publish --output ./bin/publish/win-x64 -r win-x64 -c Release --self-contained -p:PublishSingleFile=true

      - name: Upload linux-x64
        if: ${{ github.event_name == 'release' }}
        run: gh release upload ${{ github.ref_name }} "./bin/Release/publish/linux-x64/ipad-ebook-plist-editor"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload win-x64
        if: ${{ github.event_name == 'release' }}
        run: gh release upload ${{ github.ref_name }} "./bin/Release/publish/win-x64/ipad-ebook-plist-editor.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
